package com.example.e_commerceapp.core

object Utils {
    const val USER = "users"
    const val CART = "carts"
    const val EMAIL = "email"
    const val ORDER = "orders"
    const val USER_IMAGE_URL = "imageUrl"
    const val BACK4APP_USER_CLASS = "ECommercePictures"
    const val PRODUCT = "products"
    const val REVIEW = "reviews"
    const val PRODUCT_TYPE = "productType"
    const val DISCOUNT_FIELD_IN_PRODUCT = "discount"
    const val RECENTLY_VIEWED = "recentlyViewed"
    const val BACK4APP_PRODUCTS_CLASS = "ProductsImages"
    const val PRODUCT_IMAGE_URL = "productImage"
    const val BACK4APP_CREATED_AT_FIELD = "createdAt"
    const val FAVOURITE_PRODUCTS = "favoriteProducts"
    const val FAVOURITE_COUNT = "favouriteCount"
    const val CATEGORIES = "categories"
    const val CATEGORY_NAME = "categoryName"
    const val USER_ID = "userId"
    const val USER_RATE = "userRate"
    const val USER_ADDRESS = "userAddress"
    const val CHOSEN_COLOR = "color"
    const val CHOSEN_SIZE = "size"
    const val CHOSEN_AMOUNT = "productAmount"
    const val PRODUCT_ID = "productId"
    const val CART_AMOUNT = "productAmount"
    const val USER_REVIEWS_ID = "reviewsId"
    const val REVIEW_TEXT = "reviewText"
    const val DISCOUNT_COLLECTION = "discounts"
    const val DISCOUNT_VALUE_IN_DISCOUNT = "discountValue"
    const val SEARCH_KEYWORDS = "searchKeywords"
    const val USER_EMAIL = "email"
    const val USER_NAME = "userName"
    const val USER_PHONE_NUMBER = "phoneNumber"
    const val VOUCHER_COLLECTION = "vouchers"
    const val VOUCHER_TYPE = "type"

}